# Generated by Django 4.0.5 on 2022-06-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_tempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
